//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LudwigRecipe.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientList
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public Nullable<int> MeasurementId { get; set; }
        public Nullable<int> RecipeId { get; set; }
        public string ShoppingListUserId { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Measurement Measurement { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual ShoppingList ShoppingList { get; set; }
    }
}
