//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LudwigRecipe.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientListGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngredientListGroup()
        {
            this.IngredientLists = new HashSet<IngredientList>();
        }
    
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientList> IngredientLists { get; set; }
    }
}
