//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LudwigRecipe.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.HitCounts = new HashSet<HitCount>();
            this.IngredientLists = new HashSet<IngredientList>();
            this.RecipeToApplicationUsers = new HashSet<RecipeToApplicationUser>();
            this.Categories = new HashSet<Category>();
            this.SeoTags = new HashSet<SeoTag>();
            this.SubCategories = new HashSet<SubCategory>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public Nullable<int> DifficultyLevelId { get; set; }
        public Nullable<decimal> IngredientCount { get; set; }
        public string IngredientUnit { get; set; }
        public bool IsOnlyForFriends { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> MeasurementId { get; set; }
        public string Name { get; set; }
        public Nullable<int> PreparationTime { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string TeaserImageUrl { get; set; }
        public string Url { get; set; }
        public Nullable<int> WaitingTime { get; set; }
    
        public virtual DifficultyLevel DifficultyLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HitCount> HitCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientList> IngredientLists { get; set; }
        public virtual Measurement Measurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeToApplicationUser> RecipeToApplicationUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeoTag> SeoTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}
