//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LudwigRecipe.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeContent
    {
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public int ContentTypeId { get; set; }
        public string Content { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual RecipeContentType RecipeContentType { get; set; }
    }
}
